Add README
learn-co-curriculum/react-container-components pull request #1
Opened 2016-09-22 12:46 UTC by ezmiller

@thomastuts and @AnnJohn opening for review.

2016-09-26 09:45 UTC, thomastuts requested changes
Another great lesson! Two _very_ minor nits, but other than that, good to merge. Awesome job! 🚢

2016-09-26 09:45 UTC, thomastuts commented on README.md
> +* Container components are primarily concerned with *how thing work*;
how **things** work

2016-09-26 09:45 UTC, thomastuts commented on README.md
> +* they rarely have any html markup of their own, aside from a
'html' -> 'HTML'

2016-09-28 17:59 UTC, AnnJohn commented
@ezmiller could you update this and then merge? thanks!

2016-09-29 13:47 UTC, merged